import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "./styles/Home.module.css";
import Header from "@/app/components/Header";
import Info from "./components/Info";
import NetworkSwitcher from "./components/Switcher";
import { Button } from "@/components/ui/button";

const Home: NextPage = () => {
  return (
    <>
      {/* <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head> */}
      <Header />

      <main className={styles.main}>
        <Button variant="outline" className="mt-4">
          Outline Button
        </Button>
        <Info />
        <NetworkSwitcher />
      </main>
    </>
  );
};

export default Home;
